
general.import = [
"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 165, lines = 45 }
decorations = "Buttonless"
startup_mode = "Maximized"
padding.x = 5
padding.y = 5
opacity = 1
blur = false 

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 14
